### ISSUE TITLE
Search Issue on subdomain

### ISSUE THREAD

**Issue by alex-hedley** [alex-hedley/statiqweb-example#1]
In `appsettings.json` `{ "GenerateSearchIndex": true }` doesn't go to sub domain.

**Comment by alex-hedley** [comment]
`https://github.com/statiqdev/Statiq.Web/issues/1016`

**Comment by AlexHedley** [comment]
https://github.com/statiqdev/CleanBlog/commit/ad639891c4469a2c9fc1d16b0ef8f99e975e82d8
